//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACREEDOR_REL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACREEDOR_REL()
        {
            this.Diferencias_Pagos = new HashSet<Diferencias_Pagos>();
            this.DetalleConciliacionPagos = new HashSet<DetalleConciliacionPagos>();
            this.DetalleConciliacion = new HashSet<DetalleConciliacion>();
        }
    
        public int Id { get; set; }
        public int Local { get; set; }
        public Nullable<int> Cuenta { get; set; }
        public string Descripcion { get; set; }
        public string CeCo { get; set; }
        public Nullable<int> Acreedor { get; set; }
        public Nullable<int> Tipo_Pago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diferencias_Pagos> Diferencias_Pagos { get; set; }
        public virtual TIPO_PAGO TIPO_PAGO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleConciliacionPagos> DetalleConciliacionPagos { get; set; }
        public virtual CENTROS_LOCAL CENTROS_LOCAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleConciliacion> DetalleConciliacion { get; set; }
    }
}
