//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcumuladoSobrante_Faltante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcumuladoSobrante_Faltante()
        {
            this.Sobrante_Faltante = new HashSet<Sobrante_Faltante>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> TotalAcumulado { get; set; }
        public Nullable<int> CodigoTipoAceptacion { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<int> CodigoTipoRechazo { get; set; }
        public Nullable<int> Cuotas { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> idTienda { get; set; }
    
        public virtual CENTROS_LOCAL CENTROS_LOCAL { get; set; }
        public virtual TipoAceptacion TipoAceptacion { get; set; }
        public virtual TipoRechazo TipoRechazo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sobrante_Faltante> Sobrante_Faltante { get; set; }
    }
}
