//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class boletaOrigen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public boletaOrigen()
        {
            this.notaCredito = new HashSet<notaCredito>();
        }
    
        public int TRX { get; set; }
        public System.DateTime Fecha_Emision { get; set; }
        public int IdTienda { get; set; }
        public int Caja { get; set; }
        public long Nro_Boleta { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public int Tipo_Pago { get; set; }
        public string TipoDocumento { get; set; }
    
        public virtual TipoPagoGL TipoPagoGL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notaCredito> notaCredito { get; set; }
    }
}
