//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTROS_LOCAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CENTROS_LOCAL()
        {
            this.CODIGO_COMERCIO_TBK = new HashSet<CODIGO_COMERCIO_TBK>();
            this.MEDIOSPAGOS = new HashSet<MEDIOSPAGOS>();
            this.ACREEDOR_REL = new HashSet<ACREEDOR_REL>();
            this.PAGOS = new HashSet<PAGOS>();
            this.Remito = new HashSet<Remito>();
            this.Sencillos_Tiendas = new HashSet<Sencillos_Tiendas>();
            this.DetalleSencillo = new HashSet<DetalleSencillo>();
            this.AcumuladoSobrante_Faltante = new HashSet<AcumuladoSobrante_Faltante>();
            this.Sobrante_Faltante = new HashSet<Sobrante_Faltante>();
        }
    
        public long CEN_Pos { get; set; }
        public int CEN_Codigo { get; set; }
        public string CEN_Nombre { get; set; }
        public string CEN_CodigoBanco { get; set; }
        public string CEN_CuentaBanco { get; set; }
        public string CEN_Servidor { get; set; }
        public string CEN_estado { get; set; }
        public Nullable<int> IdZona { get; set; }
        public string Correo { get; set; }
    
        public virtual ZONA ZONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CODIGO_COMERCIO_TBK> CODIGO_COMERCIO_TBK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDIOSPAGOS> MEDIOSPAGOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACREEDOR_REL> ACREEDOR_REL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGOS> PAGOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remito> Remito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sencillos_Tiendas> Sencillos_Tiendas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleSencillo> DetalleSencillo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcumuladoSobrante_Faltante> AcumuladoSobrante_Faltante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sobrante_Faltante> Sobrante_Faltante { get; set; }
    }
}
