//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTROS_LOCAL1
    {
        public long CEN_Pos { get; set; }
        public int CEN_Codigo { get; set; }
        public string CEN_Nombre { get; set; }
        public string CEN_CodigoBanco { get; set; }
        public string CEN_CuentaBanco { get; set; }
        public string CEN_Servidor { get; set; }
        public string CEN_estado { get; set; }
        public Nullable<int> IdZona { get; set; }
    
        public virtual ZONA ZONA { get; set; }
    }
}
