//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODIGO_COMERCIO_TBK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CODIGO_COMERCIO_TBK()
        {
            this.Pagos_Apitbk = new HashSet<Pagos_Apitbk>();
            this.Ventas_Apitbk = new HashSet<Ventas_Apitbk>();
        }
    
        public int id { get; set; }
        public int CodigoComercio { get; set; }
        public int Local { get; set; }
        public string NombreLocal { get; set; }
        public Nullable<int> Tipo { get; set; }
    
        public virtual TIPO_PAGO TIPO_PAGO { get; set; }
        public virtual CENTROS_LOCAL CENTROS_LOCAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos_Apitbk> Pagos_Apitbk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas_Apitbk> Ventas_Apitbk { get; set; }
    }
}
