//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConciliacionAutoPagos
    {
        public string AutorizadorMp { get; set; }
        public string AutorizadorTbk { get; set; }
        public string Tarjeta { get; set; }
        public System.DateTime Fecha { get; set; }
        public int CodigoLocal { get; set; }
        public int idTienda { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaConciliacion { get; set; }
    }
}
