//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleConciliacionPagos
    {
        public string AutorizadorMp { get; set; }
        public string AutorizadorTbk { get; set; }
        public Nullable<int> CodigoLocal { get; set; }
        public Nullable<int> IdTienda { get; set; }
        public string TipoConciliacion { get; set; }
        public Nullable<System.Guid> idConciliacion { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> FechaMp { get; set; }
        public Nullable<System.DateTime> FechaTbk { get; set; }
        public Nullable<decimal> MontoMp { get; set; }
        public Nullable<decimal> MontoTbk { get; set; }
        public Nullable<short> Tipo_Pago { get; set; }
        public string TarjetaMp { get; set; }
        public string TarjetaTBk { get; set; }
        public Nullable<int> CodigoCuenta { get; set; }
        public Nullable<int> TipoAsiento { get; set; }
        public Nullable<int> TRX { get; set; }
        public Nullable<int> idAcreededor { get; set; }
        public Nullable<decimal> MontoVentatbk { get; set; }
    
        public virtual ConciliaciondePagos ConciliaciondePagos { get; set; }
        public virtual Pagos_Apitbk Pagos_Apitbk { get; set; }
        public virtual ACREEDOR_REL ACREEDOR_REL { get; set; }
        public virtual Cuenta Cuenta { get; set; }
    }
}
