//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diferencias_Pagos
    {
        public System.Guid Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Cod_Cuenta { get; set; }
        public int TipoAsiento { get; set; }
        public int Tienda { get; set; }
        public string Cod_TRX { get; set; }
        public int TRX { get; set; }
        public Nullable<System.DateTime> FechaDiferencia { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public int idTiendaAcredededor { get; set; }
        public string numeroTarjeta { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual ACREEDOR_REL ACREEDOR_REL { get; set; }
    }
}
