//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterfazAutorizacion
    {
        public string NroRef { get; set; }
        public string CodigoEmpresa { get; set; }
        public System.DateTime FechaAutorizacion { get; set; }
        public string CodigoAgencia { get; set; }
        public Nullable<int> NumeroTerminal { get; set; }
        public string NumeroBoleta { get; set; }
        public string TipoTransaccion { get; set; }
        public string CodigoUsuario { get; set; }
        public string NumeroAutorizacion { get; set; }
        public string TipoArchivo { get; set; }
        public Nullable<int> CodigoCliente { get; set; }
        public string NumeroTarjeta { get; set; }
        public Nullable<int> Monto { get; set; }
        public Nullable<int> MontoPie { get; set; }
        public Nullable<int> MesesDiferido { get; set; }
        public Nullable<int> MesesGracia { get; set; }
        public Nullable<System.DateTime> FechaAutoriza { get; set; }
        public Nullable<int> NumeroCuotas { get; set; }
        public string Extrafinanciamiento { get; set; }
        public Nullable<int> CodigoPlanCredito { get; set; }
        public Nullable<int> MontoAfecto { get; set; }
        public Nullable<int> CodigoComercio { get; set; }
        public Nullable<int> CodigoRubro { get; set; }
        public string RutVendedor { get; set; }
        public Nullable<int> CodigoPromocionVenta { get; set; }
        public Nullable<int> MontoCuota { get; set; }
        public Nullable<System.DateTime> FechaPrimerVencimiento { get; set; }
        public Nullable<System.DateTime> FechaUltimoVencimiento { get; set; }
        public string Confirmada { get; set; }
        public string ModoProceso { get; set; }
        public Nullable<int> NroTrxPos { get; set; }
        public Nullable<int> NroCaja { get; set; }
        public string TipoDiferencia { get; set; }
        public string Estado { get; set; }
        public Nullable<int> MontonoAfecto { get; set; }
    }
}
