//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroMayorDEP
    {
        public string Texto_cab_documento { get; set; }
        public string Soc { get; set; }
        public string Asignacion { get; set; }
        public string Referencia { get; set; }
        public string N_Documento { get; set; }
        public string Clase { get; set; }
        public System.DateTime Fecha_Documento { get; set; }
        public Nullable<int> CT { get; set; }
        public decimal Importe_MD { get; set; }
        public decimal Importe_ML { get; set; }
        public string Doc_Compensacion { get; set; }
        public string Usuario { get; set; }
        public string Descripcion { get; set; }
        public string Lib_mayor { get; set; }
        public Nullable<decimal> abs { get; set; }
        public System.Guid IdLibroMayor { get; set; }
        public string Texto_cab_documento1 { get; set; }
        public string Soc1 { get; set; }
        public string Asignacion1 { get; set; }
        public string Referencia1 { get; set; }
        public string N_Documento1 { get; set; }
        public string Clase1 { get; set; }
        public System.DateTime Fecha_Documento1 { get; set; }
        public Nullable<int> CT1 { get; set; }
        public decimal Importe_MD1 { get; set; }
        public decimal Importe_ML1 { get; set; }
        public string Doc_Compensacion1 { get; set; }
        public string Usuario1 { get; set; }
        public string Descripcion1 { get; set; }
        public string Lib_mayor1 { get; set; }
        public Nullable<decimal> abs1 { get; set; }
        public System.Guid IdLibroMayor1 { get; set; }
        public string Estado { get; set; }
    
        public virtual LibroMayor LibroMayor { get; set; }
        public virtual LibroMayor LibroMayor1 { get; set; }
    }
}
