//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroMayor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LibroMayor()
        {
            this.LibroMayorDEP = new HashSet<LibroMayorDEP>();
            this.LibroMayorDEP1 = new HashSet<LibroMayorDEP>();
        }
    
        public string Texto_cab_documento { get; set; }
        public string Lib_mayor { get; set; }
        public string Soc { get; set; }
        public Nullable<System.DateTime> Fecha_Compensacion { get; set; }
        public string Centro { get; set; }
        public string Asignacion { get; set; }
        public string Referencia { get; set; }
        public string N_Documento { get; set; }
        public string Div { get; set; }
        public string Clase { get; set; }
        public System.DateTime Fecha_Documento { get; set; }
        public Nullable<int> CT { get; set; }
        public decimal Importe_MD { get; set; }
        public decimal Importe_ML { get; set; }
        public string ML { get; set; }
        public string IndicadorIMP { get; set; }
        public string Doc_Compensacion { get; set; }
        public string Usuario { get; set; }
        public string Descripcion { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibroMayorDEP> LibroMayorDEP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibroMayorDEP> LibroMayorDEP1 { get; set; }
    }
}
