//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SisGesEntities3 : DbContext
    {
        public SisGesEntities3()
            : base("name=SisGesEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Sexo> Sexo { get; set; }
        public virtual DbSet<PAGOS_MP> PAGOS_MP { get; set; }
        public virtual DbSet<LIBRO_VENTA> LIBRO_VENTA { get; set; }
        public virtual DbSet<LIBRO_VENTA_PROD> LIBRO_VENTA_PROD { get; set; }
        public virtual DbSet<IDOC_PAGOS_FI> IDOC_PAGOS_FI { get; set; }
        public virtual DbSet<ConciliacionAutoPagos> ConciliacionAutoPagos { get; set; }
        public virtual DbSet<ConciliacionManualPagos> ConciliacionManualPagos { get; set; }
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<Diferencias_Pagos> Diferencias_Pagos { get; set; }
        public virtual DbSet<ACREEDOR_REL> ACREEDOR_REL { get; set; }
        public virtual DbSet<CODIGO_COMERCIO_TBK> CODIGO_COMERCIO_TBK { get; set; }
        public virtual DbSet<TIPO_PAGO> TIPO_PAGO { get; set; }
        public virtual DbSet<VENTAS> VENTAS { get; set; }
        public virtual DbSet<ZONA> ZONA { get; set; }
        public virtual DbSet<MEDIOSPAGOS> MEDIOSPAGOS { get; set; }
        public virtual DbSet<notaCreditoEspecial> notaCreditoEspecial { get; set; }
        public virtual DbSet<Conciliacion> Conciliacion { get; set; }
        public virtual DbSet<Auditoria> Auditoria { get; set; }
        public virtual DbSet<CENTROS_LOCAL> CENTROS_LOCAL { get; set; }
        public virtual DbSet<Pagos_Apitbk> Pagos_Apitbk { get; set; }
        public virtual DbSet<ConciliaciondePagos> ConciliaciondePagos { get; set; }
        public virtual DbSet<DetalleConciliacionPagos> DetalleConciliacionPagos { get; set; }
        public virtual DbSet<IDOC_FI> IDOC_FI { get; set; }
        public virtual DbSet<LibroMayor> LibroMayor { get; set; }
        public virtual DbSet<LibroMayorDEP> LibroMayorDEP { get; set; }
        public virtual DbSet<InterfazAutorizacion> InterfazAutorizacion { get; set; }
        public virtual DbSet<Periodo> Periodo { get; set; }
        public virtual DbSet<PAGOS> PAGOS { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<TipoPagoGL> TipoPagoGL { get; set; }
        public virtual DbSet<boletaOrigen> boletaOrigen { get; set; }
        public virtual DbSet<notaCredito> notaCredito { get; set; }
        public virtual DbSet<EstadoSencillo> EstadoSencillo { get; set; }
        public virtual DbSet<SencillosSAP> SencillosSAP { get; set; }
        public virtual DbSet<TipoRemito> TipoRemito { get; set; }
        public virtual DbSet<Remito> Remito { get; set; }
        public virtual DbSet<Sencillos_Tiendas> Sencillos_Tiendas { get; set; }
        public virtual DbSet<DetalleSencillo> DetalleSencillo { get; set; }
        public virtual DbSet<MontoSencillo> MontoSencillo { get; set; }
        public virtual DbSet<Sencillos> Sencillos { get; set; }
        public virtual DbSet<DetalleConciliacion> DetalleConciliacion { get; set; }
        public virtual DbSet<Ventas_Apitbk> Ventas_Apitbk { get; set; }
        public virtual DbSet<TipoAceptacion> TipoAceptacion { get; set; }
        public virtual DbSet<TipoRechazo> TipoRechazo { get; set; }
        public virtual DbSet<AcumuladoSobrante_Faltante> AcumuladoSobrante_Faltante { get; set; }
        public virtual DbSet<Sobrante_Faltante> Sobrante_Faltante { get; set; }
    
        public virtual ObjectResult<Proc_Dashboard_Detalle_Result> Proc_Dashboard_Detalle(string p_Fecha)
        {
            var p_FechaParameter = p_Fecha != null ?
                new ObjectParameter("P_Fecha", p_Fecha) :
                new ObjectParameter("P_Fecha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Dashboard_Detalle_Result>("Proc_Dashboard_Detalle", p_FechaParameter);
        }
    
        public virtual ObjectResult<Proc_Dashboard_Principal_Result> Proc_Dashboard_Principal(string p_Fecha)
        {
            var p_FechaParameter = p_Fecha != null ?
                new ObjectParameter("P_Fecha", p_Fecha) :
                new ObjectParameter("P_Fecha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Dashboard_Principal_Result>("Proc_Dashboard_Principal", p_FechaParameter);
        }
    
        public virtual ObjectResult<Proc_Dashboard_Principal_Temp_Result> Proc_Dashboard_Principal_Temp(string p_Fecha)
        {
            var p_FechaParameter = p_Fecha != null ?
                new ObjectParameter("P_Fecha", p_Fecha) :
                new ObjectParameter("P_Fecha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Dashboard_Principal_Temp_Result>("Proc_Dashboard_Principal_Temp", p_FechaParameter);
        }
    
        public virtual int Proc_GenIdocNCFC(Nullable<int> tda_I, string fecha_I)
        {
            var tda_IParameter = tda_I.HasValue ?
                new ObjectParameter("Tda_I", tda_I) :
                new ObjectParameter("Tda_I", typeof(int));
    
            var fecha_IParameter = fecha_I != null ?
                new ObjectParameter("Fecha_I", fecha_I) :
                new ObjectParameter("Fecha_I", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_GenIdocNCFC", tda_IParameter, fecha_IParameter);
        }
    
        public virtual int Proc_IdocClientes(string fecha, Nullable<int> local, string ambiente)
        {
            var fechaParameter = fecha != null ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(string));
    
            var localParameter = local.HasValue ?
                new ObjectParameter("local", local) :
                new ObjectParameter("local", typeof(int));
    
            var ambienteParameter = ambiente != null ?
                new ObjectParameter("Ambiente", ambiente) :
                new ObjectParameter("Ambiente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_IdocClientes", fechaParameter, localParameter, ambienteParameter);
        }
    
        public virtual int Proc_IdocClientesIndi_Rut(string rut, string ambiente)
        {
            var rutParameter = rut != null ?
                new ObjectParameter("Rut", rut) :
                new ObjectParameter("Rut", typeof(string));
    
            var ambienteParameter = ambiente != null ?
                new ObjectParameter("Ambiente", ambiente) :
                new ObjectParameter("Ambiente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_IdocClientesIndi_Rut", rutParameter, ambienteParameter);
        }
    
        public virtual int Proc_IMPORTAR_LIBRO_VENTA_SAP(string p_Archivo)
        {
            var p_ArchivoParameter = p_Archivo != null ?
                new ObjectParameter("P_Archivo", p_Archivo) :
                new ObjectParameter("P_Archivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_IMPORTAR_LIBRO_VENTA_SAP", p_ArchivoParameter);
        }
    
        public virtual int Proc_LeerNCFC(Nullable<int> tienda_I, string fecha_I, string ambiente)
        {
            var tienda_IParameter = tienda_I.HasValue ?
                new ObjectParameter("Tienda_I", tienda_I) :
                new ObjectParameter("Tienda_I", typeof(int));
    
            var fecha_IParameter = fecha_I != null ?
                new ObjectParameter("Fecha_I", fecha_I) :
                new ObjectParameter("Fecha_I", typeof(string));
    
            var ambienteParameter = ambiente != null ?
                new ObjectParameter("Ambiente", ambiente) :
                new ObjectParameter("Ambiente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_LeerNCFC", tienda_IParameter, fecha_IParameter, ambienteParameter);
        }
    
        public virtual ObjectResult<Proc_ListaDetalleVenta_Result> Proc_ListaDetalleVenta(string c_Fecha, string i_Tienda, string c_Tipo)
        {
            var c_FechaParameter = c_Fecha != null ?
                new ObjectParameter("C_Fecha", c_Fecha) :
                new ObjectParameter("C_Fecha", typeof(string));
    
            var i_TiendaParameter = i_Tienda != null ?
                new ObjectParameter("I_Tienda", i_Tienda) :
                new ObjectParameter("I_Tienda", typeof(string));
    
            var c_TipoParameter = c_Tipo != null ?
                new ObjectParameter("C_Tipo", c_Tipo) :
                new ObjectParameter("C_Tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_ListaDetalleVenta_Result>("Proc_ListaDetalleVenta", c_FechaParameter, i_TiendaParameter, c_TipoParameter);
        }
    
        public virtual ObjectResult<Proc_ListaIdocVenta_Result> Proc_ListaIdocVenta(string c_Fecha, string i_Tienda)
        {
            var c_FechaParameter = c_Fecha != null ?
                new ObjectParameter("C_Fecha", c_Fecha) :
                new ObjectParameter("C_Fecha", typeof(string));
    
            var i_TiendaParameter = i_Tienda != null ?
                new ObjectParameter("I_Tienda", i_Tienda) :
                new ObjectParameter("I_Tienda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_ListaIdocVenta_Result>("Proc_ListaIdocVenta", c_FechaParameter, i_TiendaParameter);
        }
    
        public virtual ObjectResult<Proc_ListaLibroVenta_Result> Proc_ListaLibroVenta(string c_Fecha, string i_Tienda, string c_Tipo)
        {
            var c_FechaParameter = c_Fecha != null ?
                new ObjectParameter("C_Fecha", c_Fecha) :
                new ObjectParameter("C_Fecha", typeof(string));
    
            var i_TiendaParameter = i_Tienda != null ?
                new ObjectParameter("I_Tienda", i_Tienda) :
                new ObjectParameter("I_Tienda", typeof(string));
    
            var c_TipoParameter = c_Tipo != null ?
                new ObjectParameter("C_Tipo", c_Tipo) :
                new ObjectParameter("C_Tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_ListaLibroVenta_Result>("Proc_ListaLibroVenta", c_FechaParameter, i_TiendaParameter, c_TipoParameter);
        }
    
        public virtual ObjectResult<Proc_ListaLibroVenta_Temp_Result> Proc_ListaLibroVenta_Temp(string c_Fecha, string i_Tienda, string c_Tipo)
        {
            var c_FechaParameter = c_Fecha != null ?
                new ObjectParameter("C_Fecha", c_Fecha) :
                new ObjectParameter("C_Fecha", typeof(string));
    
            var i_TiendaParameter = i_Tienda != null ?
                new ObjectParameter("I_Tienda", i_Tienda) :
                new ObjectParameter("I_Tienda", typeof(string));
    
            var c_TipoParameter = c_Tipo != null ?
                new ObjectParameter("C_Tipo", c_Tipo) :
                new ObjectParameter("C_Tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_ListaLibroVenta_Temp_Result>("Proc_ListaLibroVenta_Temp", c_FechaParameter, i_TiendaParameter, c_TipoParameter);
        }
    
        public virtual ObjectResult<Proc_LOCALES_ACTIVOS_Result> Proc_LOCALES_ACTIVOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_LOCALES_ACTIVOS_Result>("Proc_LOCALES_ACTIVOS");
        }
    
        public virtual ObjectResult<Proc_Locales_Transbank_Result> Proc_Locales_Transbank()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Locales_Transbank_Result>("Proc_Locales_Transbank");
        }
    
        public virtual ObjectResult<Proc_CLASE_DOCUMENTO_Result> Proc_CLASE_DOCUMENTO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_CLASE_DOCUMENTO_Result>("Proc_CLASE_DOCUMENTO");
        }
    
        public virtual ObjectResult<Proc_Dashboard_Detalle_Temp_Result> Proc_Dashboard_Detalle_Temp(string p_Fecha, string p_Centro, string p_Tipo)
        {
            var p_FechaParameter = p_Fecha != null ?
                new ObjectParameter("P_Fecha", p_Fecha) :
                new ObjectParameter("P_Fecha", typeof(string));
    
            var p_CentroParameter = p_Centro != null ?
                new ObjectParameter("P_Centro", p_Centro) :
                new ObjectParameter("P_Centro", typeof(string));
    
            var p_TipoParameter = p_Tipo != null ?
                new ObjectParameter("P_Tipo", p_Tipo) :
                new ObjectParameter("P_Tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_Dashboard_Detalle_Temp_Result>("Proc_Dashboard_Detalle_Temp", p_FechaParameter, p_CentroParameter, p_TipoParameter);
        }
    
        public virtual int Inserta_tarea(string fecha_tarea)
        {
            var fecha_tareaParameter = fecha_tarea != null ?
                new ObjectParameter("fecha_tarea", fecha_tarea) :
                new ObjectParameter("fecha_tarea", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Inserta_tarea", fecha_tareaParameter);
        }
    
        public virtual int Proc_GENERAR_VENTAS_IDOC_X_FECHA_X_LOCAL(string c_Fecha, Nullable<int> i_Tienda, string ambiente)
        {
            var c_FechaParameter = c_Fecha != null ?
                new ObjectParameter("C_Fecha", c_Fecha) :
                new ObjectParameter("C_Fecha", typeof(string));
    
            var i_TiendaParameter = i_Tienda.HasValue ?
                new ObjectParameter("I_Tienda", i_Tienda) :
                new ObjectParameter("I_Tienda", typeof(int));
    
            var ambienteParameter = ambiente != null ?
                new ObjectParameter("Ambiente", ambiente) :
                new ObjectParameter("Ambiente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_GENERAR_VENTAS_IDOC_X_FECHA_X_LOCAL", c_FechaParameter, i_TiendaParameter, ambienteParameter);
        }
    
        public virtual int Proc_GENERAR_IDOC_X_BCP(Nullable<int> p_Centro, string p_Fecha)
        {
            var p_CentroParameter = p_Centro.HasValue ?
                new ObjectParameter("P_Centro", p_Centro) :
                new ObjectParameter("P_Centro", typeof(int));
    
            var p_FechaParameter = p_Fecha != null ?
                new ObjectParameter("P_Fecha", p_Fecha) :
                new ObjectParameter("P_Fecha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_GENERAR_IDOC_X_BCP", p_CentroParameter, p_FechaParameter);
        }
    
        public virtual int Procesar_IdocClientes(string fecha, Nullable<int> local, string ambiente)
        {
            var fechaParameter = fecha != null ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(string));
    
            var localParameter = local.HasValue ?
                new ObjectParameter("local", local) :
                new ObjectParameter("local", typeof(int));
    
            var ambienteParameter = ambiente != null ?
                new ObjectParameter("Ambiente", ambiente) :
                new ObjectParameter("Ambiente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Procesar_IdocClientes", fechaParameter, localParameter, ambienteParameter);
        }
    
        public virtual int Proc_GenIdocVtaIndi_Folio(Nullable<int> tienda_I, string fecha_I, Nullable<int> nDoc, string tipoDoc, string ambiente)
        {
            var tienda_IParameter = tienda_I.HasValue ?
                new ObjectParameter("Tienda_I", tienda_I) :
                new ObjectParameter("Tienda_I", typeof(int));
    
            var fecha_IParameter = fecha_I != null ?
                new ObjectParameter("Fecha_I", fecha_I) :
                new ObjectParameter("Fecha_I", typeof(string));
    
            var nDocParameter = nDoc.HasValue ?
                new ObjectParameter("NDoc", nDoc) :
                new ObjectParameter("NDoc", typeof(int));
    
            var tipoDocParameter = tipoDoc != null ?
                new ObjectParameter("TipoDoc", tipoDoc) :
                new ObjectParameter("TipoDoc", typeof(string));
    
            var ambienteParameter = ambiente != null ?
                new ObjectParameter("Ambiente", ambiente) :
                new ObjectParameter("Ambiente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_GenIdocVtaIndi_Folio", tienda_IParameter, fecha_IParameter, nDocParameter, tipoDocParameter, ambienteParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnDiferencias_Conciliacion")]
        public virtual IQueryable<fnDiferencias_Conciliacion_Result> fnDiferencias_Conciliacion(string fecha)
        {
            var fechaParameter = fecha != null ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDiferencias_Conciliacion_Result>("[SisGesEntities3].[fnDiferencias_Conciliacion](@fecha)", fechaParameter);
        }
    
        public virtual int spInsertLibroVentas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertLibroVentas");
        }
    
        public virtual int Proc_LeerClientes_Indiv(string rut, string ambiente)
        {
            var rutParameter = rut != null ?
                new ObjectParameter("Rut", rut) :
                new ObjectParameter("Rut", typeof(string));
    
            var ambienteParameter = ambiente != null ?
                new ObjectParameter("Ambiente", ambiente) :
                new ObjectParameter("Ambiente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_LeerClientes_Indiv", rutParameter, ambienteParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnReporte_Nota_Credito")]
        public virtual IQueryable<fnReporte_Nota_Credito_Result> fnReporte_Nota_Credito(Nullable<System.DateTime> p_FechaDesde, Nullable<System.DateTime> p_FechaHasta, Nullable<int> p_Tienda)
        {
            var p_FechaDesdeParameter = p_FechaDesde.HasValue ?
                new ObjectParameter("P_FechaDesde", p_FechaDesde) :
                new ObjectParameter("P_FechaDesde", typeof(System.DateTime));
    
            var p_FechaHastaParameter = p_FechaHasta.HasValue ?
                new ObjectParameter("P_FechaHasta", p_FechaHasta) :
                new ObjectParameter("P_FechaHasta", typeof(System.DateTime));
    
            var p_TiendaParameter = p_Tienda.HasValue ?
                new ObjectParameter("P_Tienda", p_Tienda) :
                new ObjectParameter("P_Tienda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporte_Nota_Credito_Result>("[SisGesEntities3].[fnReporte_Nota_Credito](@P_FechaDesde, @P_FechaHasta, @P_Tienda)", p_FechaDesdeParameter, p_FechaHastaParameter, p_TiendaParameter);
        }
    
        [DbFunction("SisGesEntities3", "fn_Conciliacion_Automatica")]
        public virtual IQueryable<fn_Conciliacion_Automatica_Result> fn_Conciliacion_Automatica(Nullable<System.DateTime> fecha, Nullable<int> tienda)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var tiendaParameter = tienda.HasValue ?
                new ObjectParameter("Tienda", tienda) :
                new ObjectParameter("Tienda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Conciliacion_Automatica_Result>("[SisGesEntities3].[fn_Conciliacion_Automatica](@fecha, @Tienda)", fechaParameter, tiendaParameter);
        }
    
        public virtual int Proc_GenIdocNCFC_Indiv(Nullable<int> tienda_I, string fecha_I)
        {
            var tienda_IParameter = tienda_I.HasValue ?
                new ObjectParameter("Tienda_I", tienda_I) :
                new ObjectParameter("Tienda_I", typeof(int));
    
            var fecha_IParameter = fecha_I != null ?
                new ObjectParameter("Fecha_I", fecha_I) :
                new ObjectParameter("Fecha_I", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_GenIdocNCFC_Indiv", tienda_IParameter, fecha_IParameter);
        }
    
        public virtual int Proc_LeerNCFC_IND(Nullable<int> tienda_I, string fecha_I, string ambiente, string nDoc, string tipoDoc)
        {
            var tienda_IParameter = tienda_I.HasValue ?
                new ObjectParameter("Tienda_I", tienda_I) :
                new ObjectParameter("Tienda_I", typeof(int));
    
            var fecha_IParameter = fecha_I != null ?
                new ObjectParameter("Fecha_I", fecha_I) :
                new ObjectParameter("Fecha_I", typeof(string));
    
            var ambienteParameter = ambiente != null ?
                new ObjectParameter("Ambiente", ambiente) :
                new ObjectParameter("Ambiente", typeof(string));
    
            var nDocParameter = nDoc != null ?
                new ObjectParameter("NDoc", nDoc) :
                new ObjectParameter("NDoc", typeof(string));
    
            var tipoDocParameter = tipoDoc != null ?
                new ObjectParameter("TipoDoc", tipoDoc) :
                new ObjectParameter("TipoDoc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_LeerNCFC_IND", tienda_IParameter, fecha_IParameter, ambienteParameter, nDocParameter, tipoDocParameter);
        }
    
        public virtual int Proc_GenIdocMP(Nullable<int> tda_I, string fecha_I)
        {
            var tda_IParameter = tda_I.HasValue ?
                new ObjectParameter("Tda_I", tda_I) :
                new ObjectParameter("Tda_I", typeof(int));
    
            var fecha_IParameter = fecha_I != null ?
                new ObjectParameter("Fecha_I", fecha_I) :
                new ObjectParameter("Fecha_I", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_GenIdocMP", tda_IParameter, fecha_IParameter);
        }
    
        public virtual int Proc_LeerIdocMP(string fecha, Nullable<int> idTienda)
        {
            var fechaParameter = fecha != null ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(string));
    
            var idTiendaParameter = idTienda.HasValue ?
                new ObjectParameter("IdTienda", idTienda) :
                new ObjectParameter("IdTienda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_LeerIdocMP", fechaParameter, idTiendaParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnIdoc_FI")]
        public virtual IQueryable<fnIdoc_FI_Result> fnIdoc_FI(string fecha, Nullable<int> idTienda)
        {
            var fechaParameter = fecha != null ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(string));
    
            var idTiendaParameter = idTienda.HasValue ?
                new ObjectParameter("IdTienda", idTienda) :
                new ObjectParameter("IdTienda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnIdoc_FI_Result>("[SisGesEntities3].[fnIdoc_FI](@Fecha, @IdTienda)", fechaParameter, idTiendaParameter);
        }
    
        public virtual ObjectResult<Proc_TotaleMediosPagos_Result> Proc_TotaleMediosPagos(string fecha_ini, string fecha_fin, Nullable<int> codigoComercio)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("Fecha_ini", fecha_ini) :
                new ObjectParameter("Fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("Fecha_fin", fecha_fin) :
                new ObjectParameter("Fecha_fin", typeof(string));
    
            var codigoComercioParameter = codigoComercio.HasValue ?
                new ObjectParameter("CodigoComercio", codigoComercio) :
                new ObjectParameter("CodigoComercio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_TotaleMediosPagos_Result>("Proc_TotaleMediosPagos", fecha_iniParameter, fecha_finParameter, codigoComercioParameter);
        }
    
        public virtual int spInsertConciliacionAutoo(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertConciliacionAutoo", fechaParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnReporte_PagosFSP")]
        public virtual IQueryable<fnReporte_PagosFSP_Result> fnReporte_PagosFSP(Nullable<int> anio, Nullable<int> mes)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("Mes", mes) :
                new ObjectParameter("Mes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporte_PagosFSP_Result>("[SisGesEntities3].[fnReporte_PagosFSP](@Anio, @Mes)", anioParameter, mesParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnDashboard_Pagos")]
        public virtual IQueryable<fnDashboard_Pagos_Result> fnDashboard_Pagos(Nullable<System.DateTime> fecha, Nullable<int> codigoComercio)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var codigoComercioParameter = codigoComercio.HasValue ?
                new ObjectParameter("CodigoComercio", codigoComercio) :
                new ObjectParameter("CodigoComercio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDashboard_Pagos_Result>("[SisGesEntities3].[fnDashboard_Pagos](@Fecha, @CodigoComercio)", fechaParameter, codigoComercioParameter);
        }
    
        public virtual int Proc_LeerPAGOSMP(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_LeerPAGOSMP", fechaParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnUsuarioRol")]
        public virtual IQueryable<fnUsuarioRol_Result> fnUsuarioRol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnUsuarioRol_Result>("[SisGesEntities3].[fnUsuarioRol]()");
        }
    
        public virtual ObjectResult<Proc_TotalesTransbankApi_Result> Proc_TotalesTransbankApi(string fecha_ini, string fecha_fin, Nullable<int> codigoComercio)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("Fecha_ini", fecha_ini) :
                new ObjectParameter("Fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("Fecha_fin", fecha_fin) :
                new ObjectParameter("Fecha_fin", typeof(string));
    
            var codigoComercioParameter = codigoComercio.HasValue ?
                new ObjectParameter("CodigoComercio", codigoComercio) :
                new ObjectParameter("CodigoComercio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_TotalesTransbankApi_Result>("Proc_TotalesTransbankApi", fecha_iniParameter, fecha_finParameter, codigoComercioParameter);
        }
    
        public virtual int Proc_DESCARGA_VENTAS_IDOC_X_FECHA_X_LOCAL(string c_Fecha, Nullable<int> i_Tienda)
        {
            var c_FechaParameter = c_Fecha != null ?
                new ObjectParameter("C_Fecha", c_Fecha) :
                new ObjectParameter("C_Fecha", typeof(string));
    
            var i_TiendaParameter = i_Tienda.HasValue ?
                new ObjectParameter("I_Tienda", i_Tienda) :
                new ObjectParameter("I_Tienda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_DESCARGA_VENTAS_IDOC_X_FECHA_X_LOCAL", c_FechaParameter, i_TiendaParameter);
        }
    
        public virtual int Proc_IDOC_X_BCP_IND()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_IDOC_X_BCP_IND");
        }
    
        public virtual int Proc_IDOC_VENTA(Nullable<int> i_Tienda, string c_Fecha, string ambiente)
        {
            var i_TiendaParameter = i_Tienda.HasValue ?
                new ObjectParameter("I_Tienda", i_Tienda) :
                new ObjectParameter("I_Tienda", typeof(int));
    
            var c_FechaParameter = c_Fecha != null ?
                new ObjectParameter("C_Fecha", c_Fecha) :
                new ObjectParameter("C_Fecha", typeof(string));
    
            var ambienteParameter = ambiente != null ?
                new ObjectParameter("Ambiente", ambiente) :
                new ObjectParameter("Ambiente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_IDOC_VENTA", i_TiendaParameter, c_FechaParameter, ambienteParameter);
        }
    
        public virtual int Proc_IdocClientes2(string fecha, Nullable<int> local, string ambiente)
        {
            var fechaParameter = fecha != null ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(string));
    
            var localParameter = local.HasValue ?
                new ObjectParameter("local", local) :
                new ObjectParameter("local", typeof(int));
    
            var ambienteParameter = ambiente != null ?
                new ObjectParameter("Ambiente", ambiente) :
                new ObjectParameter("Ambiente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_IdocClientes2", fechaParameter, localParameter, ambienteParameter);
        }
    
        public virtual int Proc_IDOC_VENTA_IND(Nullable<int> i_Tienda, string c_Fecha, string ambiente)
        {
            var i_TiendaParameter = i_Tienda.HasValue ?
                new ObjectParameter("I_Tienda", i_Tienda) :
                new ObjectParameter("I_Tienda", typeof(int));
    
            var c_FechaParameter = c_Fecha != null ?
                new ObjectParameter("C_Fecha", c_Fecha) :
                new ObjectParameter("C_Fecha", typeof(string));
    
            var ambienteParameter = ambiente != null ?
                new ObjectParameter("Ambiente", ambiente) :
                new ObjectParameter("Ambiente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_IDOC_VENTA_IND", i_TiendaParameter, c_FechaParameter, ambienteParameter);
        }
    
        public virtual int Proc_GenIdocCLI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_GenIdocCLI");
        }
    
        public virtual int Proc_GenIdocClientes_Indiv()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_GenIdocClientes_Indiv");
        }
    
        [DbFunction("SisGesEntities3", "fnDashboard_Detalle_Temp")]
        public virtual IQueryable<fnDashboard_Detalle_Temp_Result> fnDashboard_Detalle_Temp(string p_Fecha)
        {
            var p_FechaParameter = p_Fecha != null ?
                new ObjectParameter("P_Fecha", p_Fecha) :
                new ObjectParameter("P_Fecha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDashboard_Detalle_Temp_Result>("[SisGesEntities3].[fnDashboard_Detalle_Temp](@P_Fecha)", p_FechaParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnReporte_Participacion")]
        public virtual IQueryable<fnReporte_Participacion_Result> fnReporte_Participacion(Nullable<int> anio, Nullable<int> mes, Nullable<int> tienda)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("Mes", mes) :
                new ObjectParameter("Mes", typeof(int));
    
            var tiendaParameter = tienda.HasValue ?
                new ObjectParameter("Tienda", tienda) :
                new ObjectParameter("Tienda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporte_Participacion_Result>("[SisGesEntities3].[fnReporte_Participacion](@Anio, @Mes, @Tienda)", anioParameter, mesParameter, tiendaParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnReporte_TicketPromedio")]
        public virtual IQueryable<fnReporte_TicketPromedio_Result> fnReporte_TicketPromedio(Nullable<int> anio, Nullable<int> mes, Nullable<int> tienda)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("Mes", mes) :
                new ObjectParameter("Mes", typeof(int));
    
            var tiendaParameter = tienda.HasValue ?
                new ObjectParameter("Tienda", tienda) :
                new ObjectParameter("Tienda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporte_TicketPromedio_Result>("[SisGesEntities3].[fnReporte_TicketPromedio](@Anio, @Mes, @Tienda)", anioParameter, mesParameter, tiendaParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnReporte_Avance")]
        public virtual IQueryable<fnReporte_Avance_Result> fnReporte_Avance(Nullable<int> anio, Nullable<int> mes, Nullable<int> tienda)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("Mes", mes) :
                new ObjectParameter("Mes", typeof(int));
    
            var tiendaParameter = tienda.HasValue ?
                new ObjectParameter("Tienda", tienda) :
                new ObjectParameter("Tienda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporte_Avance_Result>("[SisGesEntities3].[fnReporte_Avance](@Anio, @Mes, @Tienda)", anioParameter, mesParameter, tiendaParameter);
        }
    
        public virtual int spConciliacionAutomatica(Nullable<System.DateTime> fecha, Nullable<System.Guid> id)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spConciliacionAutomatica", fechaParameter, idParameter);
        }
    
        [DbFunction("SisGesEntities3", "fn_Conciliacion_Manual_aPI")]
        public virtual IQueryable<fn_Conciliacion_Manual_aPI_Result> fn_Conciliacion_Manual_aPI(Nullable<System.DateTime> fecha, Nullable<int> local)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var localParameter = local.HasValue ?
                new ObjectParameter("local", local) :
                new ObjectParameter("local", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Conciliacion_Manual_aPI_Result>("[SisGesEntities3].[fn_Conciliacion_Manual_aPI](@fecha, @local)", fechaParameter, localParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnIdocPagos_FI")]
        public virtual IQueryable<fnIdocPagos_FI_Result> fnIdocPagos_FI(string fecha, Nullable<int> idTienda)
        {
            var fechaParameter = fecha != null ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(string));
    
            var idTiendaParameter = idTienda.HasValue ?
                new ObjectParameter("IdTienda", idTienda) :
                new ObjectParameter("IdTienda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnIdocPagos_FI_Result>("[SisGesEntities3].[fnIdocPagos_FI](@Fecha, @IdTienda)", fechaParameter, idTiendaParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnIdocVentas_FI")]
        public virtual IQueryable<fnIdocVentas_FI_Result> fnIdocVentas_FI(string fecha, Nullable<int> idTienda)
        {
            var fechaParameter = fecha != null ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(string));
    
            var idTiendaParameter = idTienda.HasValue ?
                new ObjectParameter("IdTienda", idTienda) :
                new ObjectParameter("IdTienda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnIdocVentas_FI_Result>("[SisGesEntities3].[fnIdocVentas_FI](@Fecha, @IdTienda)", fechaParameter, idTiendaParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnIdocVentas_MP")]
        public virtual IQueryable<fnIdocVentas_MP_Result> fnIdocVentas_MP(string fecha, Nullable<int> idTienda)
        {
            var fechaParameter = fecha != null ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(string));
    
            var idTiendaParameter = idTienda.HasValue ?
                new ObjectParameter("IdTienda", idTienda) :
                new ObjectParameter("IdTienda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnIdocVentas_MP_Result>("[SisGesEntities3].[fnIdocVentas_MP](@Fecha, @IdTienda)", fechaParameter, idTiendaParameter);
        }
    
        [DbFunction("SisGesEntities3", "Fn_NC_Especial")]
        public virtual IQueryable<Fn_NC_Especial_Result> Fn_NC_Especial(Nullable<System.DateTime> inicio, Nullable<System.DateTime> fin)
        {
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("Inicio", inicio) :
                new ObjectParameter("Inicio", typeof(System.DateTime));
    
            var finParameter = fin.HasValue ?
                new ObjectParameter("Fin", fin) :
                new ObjectParameter("Fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_NC_Especial_Result>("[SisGesEntities3].[Fn_NC_Especial](@Inicio, @Fin)", inicioParameter, finParameter);
        }
    
        public virtual int spInsertConciliacionAutoPagos(Nullable<System.DateTime> fecha, Nullable<System.Guid> id)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertConciliacionAutoPagos", fechaParameter, idParameter);
        }
    
        [DbFunction("SisGesEntities3", "fn_ConciliacionPagos_Manual_aPI")]
        public virtual IQueryable<fn_ConciliacionPagos_Manual_aPI_Result> fn_ConciliacionPagos_Manual_aPI(Nullable<System.DateTime> fecha, Nullable<int> local)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var localParameter = local.HasValue ?
                new ObjectParameter("local", local) :
                new ObjectParameter("local", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ConciliacionPagos_Manual_aPI_Result>("[SisGesEntities3].[fn_ConciliacionPagos_Manual_aPI](@fecha, @local)", fechaParameter, localParameter);
        }
    
        [DbFunction("SisGesEntities3", "Fn_PAGOS_Cuenta_Rut")]
        public virtual IQueryable<Fn_PAGOS_Cuenta_Rut_Result> Fn_PAGOS_Cuenta_Rut(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_PAGOS_Cuenta_Rut_Result>("[SisGesEntities3].[Fn_PAGOS_Cuenta_Rut](@Fecha)", fechaParameter);
        }
    
        [DbFunction("SisGesEntities3", "Fn_MP_Cuenta_Rut")]
        public virtual IQueryable<Fn_MP_Cuenta_Rut_Result> Fn_MP_Cuenta_Rut(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_MP_Cuenta_Rut_Result>("[SisGesEntities3].[Fn_MP_Cuenta_Rut](@Fecha)", fechaParameter);
        }
    
        public virtual int spInser_detallelibromayor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInser_detallelibromayor");
        }
    
        public virtual int spInsertConciliacionAuto_LibMayor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertConciliacionAuto_LibMayor");
        }
    
        public virtual int spConciliacionAutomaticaCAAU(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spConciliacionAutomaticaCAAU", fechaParameter);
        }
    
        public virtual ObjectResult<AperturaPeriodo_Result> AperturaPeriodo(Nullable<int> ano, Nullable<int> mes)
        {
            var anoParameter = ano.HasValue ?
                new ObjectParameter("Ano", ano) :
                new ObjectParameter("Ano", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("Mes", mes) :
                new ObjectParameter("Mes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AperturaPeriodo_Result>("AperturaPeriodo", anoParameter, mesParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnReporte_CAAU")]
        public virtual IQueryable<fnReporte_CAAU_Result> fnReporte_CAAU(Nullable<System.DateTime> fecha, string estado)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporte_CAAU_Result>("[SisGesEntities3].[fnReporte_CAAU](@Fecha, @Estado)", fechaParameter, estadoParameter);
        }
    
        public virtual int spConAutomaticaSencilloSAP(Nullable<System.DateTime> fechainicio, Nullable<System.DateTime> fechaFin)
        {
            var fechainicioParameter = fechainicio.HasValue ?
                new ObjectParameter("Fechainicio", fechainicio) :
                new ObjectParameter("Fechainicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spConAutomaticaSencilloSAP", fechainicioParameter, fechaFinParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnSencillosTiendaNoConciliados")]
        public virtual IQueryable<fnSencillosTiendaNoConciliados_Result> fnSencillosTiendaNoConciliados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnSencillosTiendaNoConciliados_Result>("[SisGesEntities3].[fnSencillosTiendaNoConciliados]()");
        }
    
        [DbFunction("SisGesEntities3", "fnReporteBoletasContraloria")]
        public virtual IQueryable<fnReporteBoletasContraloria_Result> fnReporteBoletasContraloria(Nullable<int> year, Nullable<int> month)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteBoletasContraloria_Result>("[SisGesEntities3].[fnReporteBoletasContraloria](@year, @month)", yearParameter, monthParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnReporteNCContraloria")]
        public virtual IQueryable<fnReporteNCContraloria_Result> fnReporteNCContraloria(Nullable<System.DateTime> fechainicio, Nullable<System.DateTime> fechaFin)
        {
            var fechainicioParameter = fechainicio.HasValue ?
                new ObjectParameter("Fechainicio", fechainicio) :
                new ObjectParameter("Fechainicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteNCContraloria_Result>("[SisGesEntities3].[fnReporteNCContraloria](@Fechainicio, @FechaFin)", fechainicioParameter, fechaFinParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnReporte_Ventas")]
        public virtual IQueryable<fnReporte_Ventas_Result> fnReporte_Ventas(Nullable<int> anio, Nullable<int> mes, Nullable<int> tienda)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("Mes", mes) :
                new ObjectParameter("Mes", typeof(int));
    
            var tiendaParameter = tienda.HasValue ?
                new ObjectParameter("Tienda", tienda) :
                new ObjectParameter("Tienda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporte_Ventas_Result>("[SisGesEntities3].[fnReporte_Ventas](@Anio, @Mes, @Tienda)", anioParameter, mesParameter, tiendaParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnReporte_CAAU_AVANCES")]
        public virtual IQueryable<fnReporte_CAAU_AVANCES_Result> fnReporte_CAAU_AVANCES(Nullable<System.DateTime> fecha, string estado)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporte_CAAU_AVANCES_Result>("[SisGesEntities3].[fnReporte_CAAU_AVANCES](@Fecha, @Estado)", fechaParameter, estadoParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnReporte_PremisasNC")]
        public virtual IQueryable<fnReporte_PremisasNC_Result> fnReporte_PremisasNC(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporte_PremisasNC_Result>("[SisGesEntities3].[fnReporte_PremisasNC](@Fecha)", fechaParameter);
        }
    
        [DbFunction("SisGesEntities3", "fnReporte_CAPA_PAGOS")]
        public virtual IQueryable<fnReporte_CAPA_PAGOS_Result> fnReporte_CAPA_PAGOS(Nullable<System.DateTime> fecha, string estado)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporte_CAPA_PAGOS_Result>("[SisGesEntities3].[fnReporte_CAPA_PAGOS](@Fecha, @Estado)", fechaParameter, estadoParameter);
        }
    
        public virtual int spConciliacionAutomaticaCAPA(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spConciliacionAutomaticaCAPA", fechaParameter);
        }
    
        [DbFunction("SisGesEntities3", "fn_ReporteNcFULLCuadratura")]
        public virtual IQueryable<fn_ReporteNcFULLCuadratura_Result> fn_ReporteNcFULLCuadratura(Nullable<System.DateTime> fechaInicioNotaCredito, Nullable<System.DateTime> fechaFinNotaCredito)
        {
            var fechaInicioNotaCreditoParameter = fechaInicioNotaCredito.HasValue ?
                new ObjectParameter("FechaInicioNotaCredito", fechaInicioNotaCredito) :
                new ObjectParameter("FechaInicioNotaCredito", typeof(System.DateTime));
    
            var fechaFinNotaCreditoParameter = fechaFinNotaCredito.HasValue ?
                new ObjectParameter("FechaFinNotaCredito", fechaFinNotaCredito) :
                new ObjectParameter("FechaFinNotaCredito", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ReporteNcFULLCuadratura_Result>("[SisGesEntities3].[fn_ReporteNcFULLCuadratura](@FechaInicioNotaCredito, @FechaFinNotaCredito)", fechaInicioNotaCreditoParameter, fechaFinNotaCreditoParameter);
        }
    }
}
