//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOS_MP
    {
        public string MANDT { get; set; }
        public string INTERFAZ { get; set; }
        public string FECHAINT { get; set; }
        public int CORRELAT { get; set; }
        public int NITEM { get; set; }
        public string BUKRS { get; set; }
        public string BLART { get; set; }
        public string WAERS { get; set; }
        public string BUDAT { get; set; }
        public string BLDAT { get; set; }
        public string MONAT { get; set; }
        public int XBLNR { get; set; }
        public string BKTXT { get; set; }
        public string BUPLA { get; set; }
        public string NEWBS { get; set; }
        public string NEWKO { get; set; }
        public string NEWUM { get; set; }
        public string NEWBK { get; set; }
        public decimal WRBTR { get; set; }
        public string FWBAS { get; set; }
        public string MWSKZ { get; set; }
        public string GSBER { get; set; }
        public string KOSTL_PRCTR { get; set; }
        public string AUFNR { get; set; }
        public string ZTERM { get; set; }
        public string ZUONR { get; set; }
        public string SGTXT { get; set; }
        public string VBUND { get; set; }
        public string XREF1 { get; set; }
        public string XREF2 { get; set; }
        public string XREF3 { get; set; }
        public string VALUT { get; set; }
        public string XMWST { get; set; }
        public string ZLSPR { get; set; }
        public string ZFBDT { get; set; }
        public string MANSP { get; set; }
        public string NEWBW { get; set; }
        public string MENGE { get; set; }
        public string KURSF { get; set; }
        public string WWERT { get; set; }
        public string PRCTR { get; set; }
        public string SKFBT { get; set; }
        public string NAME1 { get; set; }
        public string ORT01 { get; set; }
        public string STCD1 { get; set; }
        public string EBELN { get; set; }
        public string WERKS { get; set; }
    }
}
