//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remito
    {
        public string Codigo { get; set; }
        public int idTienda { get; set; }
        public Nullable<System.Guid> idSencillosTienda { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> CodigoTipoRemito { get; set; }
        public string NumeroDepostio { get; set; }
    
        public virtual CENTROS_LOCAL CENTROS_LOCAL { get; set; }
        public virtual Sencillos_Tiendas Sencillos_Tiendas { get; set; }
        public virtual TipoRemito TipoRemito { get; set; }
    }
}
