//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sencillos_Tiendas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sencillos_Tiendas()
        {
            this.Remito = new HashSet<Remito>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<System.Guid> idDetalleSencillo { get; set; }
        public Nullable<int> CodigoEstadoSencillo { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public Nullable<int> idTienda { get; set; }
    
        public virtual CENTROS_LOCAL CENTROS_LOCAL { get; set; }
        public virtual EstadoSencillo EstadoSencillo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remito> Remito { get; set; }
        public virtual DetalleSencillo DetalleSencillo { get; set; }
    }
}
