//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sobrante_Faltante
    {
        public int IDTIENDA { get; set; }
        public System.DateTime FECHA { get; set; }
        public string MEDIO_PAGO { get; set; }
        public int CAJA { get; set; }
        public int TOTAL { get; set; }
        public string TIPO_CIERRE { get; set; }
        public string TIPO { get; set; }
        public System.DateTime FECHHORA { get; set; }
        public Nullable<int> MARCA { get; set; }
        public string ID_Empleado { get; set; }
        public Nullable<System.Guid> IdAcumulado { get; set; }
    
        public virtual AcumuladoSobrante_Faltante AcumuladoSobrante_Faltante { get; set; }
        public virtual CENTROS_LOCAL CENTROS_LOCAL { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
